
title: showpriest
desctiption: showpriest is a responsive jekyll theme which includes pinterest like pins.
url: "https://showpriest.github.io"
permalink: ":title/"

category_list: [ akb48, nmb48, stu48, nogizaka46, sakurazaka46, hinatazaka46, babababambi ]

markdown: kramdown
baseurl: ""
full-version: "https://showpriest.github.io"

sass:
    style: compressed

  
#optimization
#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

highlight: rouge


# Tracker
analytics: UA-83979019-1

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:   

include: [_pages]
version: 0.8

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag
